
- action: read
  fields: '*'
  roles:
    - 901ead82-3e1e-4b81-a876-0b36638ff1d9
    - ae0f8645-b4c3-4d80-b866-6f9c4b2d47f6

- action: read
  fields:
    - coordinators
    - event
    - id
    - name
    - registrations
  roles:
    - ce23293b-3719-435a-aa6d-e9efa90adf83

- action: update
  fields: '*'
  roles:
    - ae0f8645-b4c3-4d80-b866-6f9c4b2d47f6

- action: create
  fields: '*'
  roles:
    - ae0f8645-b4c3-4d80-b866-6f9c4b2d47f6

- action: read
  fields:
    - coordinators
    - event
    - id
    - name
    - registrations
  permissions:
    _and:
      - coordinators:
          user:
            _eq: $CURRENT_USER
  roles:
    - aa37ee67-b2b6-4ffa-8987-a9f7ae86be51

- action: update
  fields:
    - coordinators
    - name
    - registrations
  roles:
    - 901ead82-3e1e-4b81-a876-0b36638ff1d9
