
- action: read
  fields: '*'
  permissions:
    _and:
      - has_role:
          user:
            _eq: $CURRENT_USER
  roles:
    - 901ead82-3e1e-4b81-a876-0b36638ff1d9
    - aa37ee67-b2b6-4ffa-8987-a9f7ae86be51

- action: read
  permissions:
    _and:
      - has_role:
          user:
            _eq: $CURRENT_USER
  roles:
    - ce23293b-3719-435a-aa6d-e9efa90adf83
