
- action: read
  fields: '*'
  permissions:
    _or:
      - role:
          _eq: $CURRENT_ROLE
      - role:
          _null: true
  roles:
    - aa37ee67-b2b6-4ffa-8987-a9f7ae86be51

- action: create
  fields: '*'
  roles:
    - aa37ee67-b2b6-4ffa-8987-a9f7ae86be51

- action: update
  fields: '*'
  permissions:
    user_created:
      _eq: $CURRENT_USER
  roles:
    - aa37ee67-b2b6-4ffa-8987-a9f7ae86be51

- action: delete
  fields: '*'
  permissions:
    user_created:
      _eq: $CURRENT_USER
  roles:
    - aa37ee67-b2b6-4ffa-8987-a9f7ae86be51
