
- action: read
  fields:
    - activities
    - age
    - allergy
    - date_updated
    - event
    - gender
    - group
    - id
    - name
    - personId
    - relations
    - room
    - status
    - user
  permissions:
    group:
      users:
        user:
          _eq: $CURRENT_USER
  roles:
    - ce23293b-3719-435a-aa6d-e9efa90adf83

- action: update
  fields:
    - allergy
    - room
  permissions:
    _and:
      - group:
          users:
            user:
              _eq: $CURRENT_USER
      - event:
          deadline:
            _gt: $NOW
  roles:
    - ce23293b-3719-435a-aa6d-e9efa90adf83

- action: read
  fields: '*'
  roles:
    - 901ead82-3e1e-4b81-a876-0b36638ff1d9
    - ae0f8645-b4c3-4d80-b866-6f9c4b2d47f6

- action: create
  fields: '*'
  roles:
    - 901ead82-3e1e-4b81-a876-0b36638ff1d9
    - ae0f8645-b4c3-4d80-b866-6f9c4b2d47f6

- action: update
  fields: '*'
  roles:
    - 901ead82-3e1e-4b81-a876-0b36638ff1d9
    - ae0f8645-b4c3-4d80-b866-6f9c4b2d47f6

- action: delete
  fields: '*'
  roles:
    - 901ead82-3e1e-4b81-a876-0b36638ff1d9

- action: read
  fields:
    - activities
    - age
    - date_updated
    - event
    - gender
    - group
    - id
    - name
    - person_id
    - relations
    - status
    - tags
    - user
  permissions:
    _and:
      - activities:
          activity:
            coordinators:
              user:
                _contains: $CURRENT_USER
  roles:
    - aa37ee67-b2b6-4ffa-8987-a9f7ae86be51
